

campau.1 <- subset(sec1, sp=="CAMPAU")
campau.2 <- subset(sec2, sp=="CAMPAU")
campau.3 <- subset(sec3, sp=="CAMPAU")
table(campau.1$size)
table(campau.2$size)
table(campau.3$size)
adindu.1 <- subset(sec1, sp=="ADINDU")
adindu.2 <- subset(sec2, sp=="ADINDU")
adindu.3 <- subset(sec3, sp=="ADINDU")
table(adindu.1$size)
table(adindu.2$size)
table(adindu.3$size)
dillsu.1 <- subset(sec1, sp=="DILLSU")
dillsu.2 <- subset(sec2, sp=="DILLSU")
dillsu.3 <- subset(sec3, sp=="DILLSU")
table(dillsu.1$size)
table(dillsu.2$size)
table(dillsu.3$size)
rhodci.1 <- subset(sec1, sp=="RHODCI")
rhodci.2 <- subset(sec2, sp=="RHODCI")
rhodci.3 <- subset(sec3, sp=="RHODCI")
table(rhodci.1$size)
table(rhodci.2$size)
table(rhodci.3$size)
timowa.1 <- subset(sec1, sp=="TIMOWA")
timowa.2 <- subset(sec2, sp=="TIMOWA")
timowa.3 <- subset(sec3, sp=="TIMOWA")
table(timowa.1$size)
table(timowa.2$size)
table(timowa.3$size)
ficugr.1 <- subset(sec1, sp=="FICUGR")
ficugr.2 <- subset(sec2, sp=="FICUGR")
ficugr.3 <- subset(sec3, sp=="FICUGR")
table(ficugr.1$size)
table(ficugr.2$size)
table(ficugr.3$size)
streel.1 <- subset(sec1, sp=="STREEL")
streel.2 <- subset(sec2, sp=="STREEL")
streel.3 <- subset(sec3, sp=="STREEL")
table(streel.1$size)
table(streel.2$size)
table(streel.3$size)

